# Air config for live reload
root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["tmp"]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = true
  follow_symlink = false
  include_ext = ["go", "html", "toml", "json"]
  include_dir = []
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
