{
  inputs,
  globals,
  config,
  pkgs,
  lib,
  ...
}:
let
  host = config.node.name;
  nebulaIp = globals.nebula.mesh.hosts.${host}.ipv4;

  masterNode = "athena"; # this is dynamically determined by the sentinel at runtime
  masterName = "mymaster";

  masterNebulaIp = globals.nebula.mesh.hosts.${masterNode}.ipv4;

  isMaster = host == masterNode;
in
{

  environment.systemPackages = with pkgs; [ valkey ];

  users.groups.redis = { };
  users.users.redis = {
    isSystemUser = true;
    group = "redis";
  };

  # Persist Valkey data
  environment.persistence."/persist".directories = lib.singleton {
    directory = "/var/lib/redis-server";
    mode = "0700";
    user = "redis";
    group = "redis";
  };

  age.secrets.valkey-server-password = {
    rekeyFile = inputs.self.outPath + "/secrets/generated/valkey-server-password.age";
    generator.script = "alnum";
    owner = config.services.redis.servers.server.user;
  };

  age.secrets.valkey-sentinel-password = {
    rekeyFile = inputs.self.outPath + "/secrets/generated/valkey-sentinel-password.age";
    generator.script = "alnum";
    owner = config.services.redis.servers.sentinel.user;
  };

  # Configure both Redis server and Sentinel instances
  services.redis = {
    package = pkgs.valkey;

    servers = {
      server = {
        enable = true;
        user = "redis";

        port = 6379;
        bind = nebulaIp;

        requirePassFile = config.age.secrets.valkey-server-password.path;

        settings = {
          maxmemory = "256m";
          maxmemory-policy = "allkeys-lru";
          replica-read-only = "yes";
          replicaof = lib.mkIf (!isMaster) "${masterNebulaIp} 6379";
        };
      };

      # Sentinel instance for automatic failover
      sentinel = {
        user = "redis";
        enable = true;
        port = 26379;
        bind = nebulaIp;
        extraParams = [ "--sentinel" ];

        requirePassFile = config.age.secrets.valkey-sentinel-password.path;

        settings = {
          sentinel = [
            "monitor ${masterName} ${masterNebulaIp} 6379 2"
            "down-after-milliseconds ${masterName} 30000"
            "failover-timeout ${masterName} 180000"
            "parallel-syncs ${masterName} 1"
          ];
        };
      };
    };
  };

  systemd.services.redis-server = {
    serviceConfig.ExecStartPre = lib.mkAfter [
      (
        "+"
        + pkgs.writeShellScript "redis-masterauth" ''
          {
            echo -n "masterauth "
            cat ${config.age.secrets.valkey-server-password.path}
          } >> "/run/redis-server/nixos.conf"
        ''
      )
    ];
  };

  systemd.services.redis-sentinel = {
    serviceConfig.ExecStartPre = lib.mkAfter [
      (
        "+"
        + pkgs.writeShellScript "redis-sentinel-auth-pass" ''
          # We delete the dynamic config section that Redis Sentinel generates, in order to
          # always use this config as source of truth. Essentialy, redis sentinel will take
          # our whole config, and adds that content to /var/lib/redis-sentinel/redis.conf,
          # so we can't manage it anymore, so we delete it.
          sed -i '/# Generated by CONFIG REWRITE/,$d' /var/lib/redis-sentinel/redis.conf
          {
            echo -n "sentinel auth-pass ${masterName} "
            cat ${config.age.secrets.valkey-server-password.path}
          } >> "/run/redis-sentinel/nixos.conf"
        ''
      )
    ];
  };

  consul.services = {
    redis =
      let
        inherit (config.services.redis.servers.server) port bind;
      in
      {
        name = "redis";
        inherit port;

        check = {
          tcp = "${bind}:${toString port}";
          interval = "10s";
          timeout = "2s";
        };

        tags = [ "server" ];
      };

    redis-sentinel =
      let
        inherit (config.services.redis.servers.sentinel) port bind;
      in
      {
        name = "redis";
        inherit port;

        check = {
          tcp = "${bind}:${toString port}";
          interval = "10s";
          timeout = "2s";
        };

        tags = [ "sentinel" ];
      };
  };

  systemd.services.consul-redis-role-sync = {
    description = "Sync Redis role tag in Consul";
    after = [
      "consul.service"
      "redis.service"
    ];
    requires = [ "consul.service" ];

    serviceConfig = {
      Type = "oneshot";
      DynamicUser = true;
      LoadCredential = "valkey-sentinel-password:${config.age.secrets.valkey-sentinel-password.path}";

      ExecStart = pkgs.writeShellScript "consul-redis-role-sync" ''
        set -euo pipefail

        SENTINEL_PORT="26379"
        MASTER_NAME="${masterName}"
        LOCAL_IP="${nebulaIp}"
        CONSUL_API="http://$LOCAL_IP:8500"
        SERVICE_ID="redis"

        export VALKEYCLI_AUTH=$(cat "$CREDENTIALS_DIRECTORY/valkey-sentinel-password")

        MASTER_IP=$(${pkgs.valkey}/bin/redis-cli -h "$LOCAL_IP" -p "$SENTINEL_PORT" \
          SENTINEL get-master-addr-by-name "$MASTER_NAME" | head -1)

        ROLE=$( [ "$MASTER_IP" = "$LOCAL_IP" ] && echo "master" || echo "slave" )

        SERVICE=$(${pkgs.curl}/bin/curl -sf "$CONSUL_API/v1/agent/service/$SERVICE_ID")

        PAYLOAD=$(echo "$SERVICE" | ${pkgs.jq}/bin/jq -c \
          --arg role "$ROLE" \
          '.Name = .Service | del(.Service) | del(.ContentHash) | del(.Datacenter) |
          if .Tags | index($role) then null else .Tags = [$role, "server"] end')

        if [ "$PAYLOAD" != "null" ]; then
          ${pkgs.curl}/bin/curl -X PUT "$CONSUL_API/v1/agent/service/register" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
        fi
      '';
    };
  };

  systemd.timers.consul-redis-role-sync = {
    description = "Timer for Consul Redis role sync";
    wantedBy = [ "timers.target" ];

    timerConfig = {
      OnBootSec = "30s";
      OnUnitActiveSec = "15s";
      Unit = "consul-redis-role-sync.service";
    };
  };

  globals.nebula.mesh.hosts.${host}.firewall.inbound = [
    {
      inherit (config.services.redis.servers.server) port;
      proto = "tcp";
      group = "any"; # TODO: restrict this
    }
    {
      inherit (config.services.redis.servers.sentinel) port;
      proto = "tcp";
      group = "any";
    }
  ];
}
