creation_rules:
  - path_regex: .*
    age: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOg0phKMml4tg+kH2qZOUVi9NT6roXfiDRTLJ4Si3xtP,age1yubikey1qw8ddwxjsp2zdrajc5kk2m3ccv83f74yu3cjujfs8kfq823vqv6k2zyta6a,age1yubikey1q0wmqzjaxwgndf94hd7t37dx7wd45qwwk0r7zfytkasd6f5lvc70w89lwgg
