creation_rules:
- age:
  - age1yubikey1qw8ddwxjsp2zdrajc5kk2m3ccv83f74yu3cjujfs8kfq823vqv6k2zyta6a
  - age1yubikey1q0wmqzjaxwgndf94hd7t37dx7wd45qwwk0r7zfytkasd6f5lvc70w89lwgg
  hc_vault_transit_uri: https://vault.local.salamon.xyz/v1/transit/keys/sops-key
  path_regex: .*

