pushover_app_key: ENC[AES256_GCM,data:ykZCSaLmHNMu2XYq1/7DRUoHHGHRc87nTEAfhSPj,iv:SHRPSVoV1Z1ST0dyVNWvqIcbWRedp1YkRa4JGS9OuN4=,tag:QJQVzsvycLyPsL1Zhc7COA==,type:str]
pushover_user_key: ENC[AES256_GCM,data:gdehfiJTq+23HrKXyKBa2Lxl05U2UNjPbj0Q18Gy,iv:gwwkbmvGM565hUJJcE6xgY/5yK/PSII1YzCZkQu2BP0=,tag:9GP9gm7+CeNmnq+Awkf9IA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOg0phKMml4tg+kH2qZOUVi9NT6roXfiDRTLJ4Si3xtP
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHg0VmZ1USBKbmJZ
            RXdUbHVtbzFsRFpFQ3l3RU5DcFVMalg4TFZjTk9DYVh0QWNRMnh3Cmt3amNPMkhn
            K3piM0pES2R3RVM3TnptbVV3WGtQOXJSQjAzNFZQQkxWK28KLS0tIGo4YmNtZlpa
            V3FNWEdDVGZNWGJPNi84d01EUWZKUnBLUDFQcElEOUIySTgK+CftmFMDfq2ak5WQ
            lLFXsLp6D/aRqEUfoS+iWb+pQ4B+N2C+cCeBcX1hHmspxhLltQuODpNiS6WTW89P
            nZlhjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qw8ddwxjsp2zdrajc5kk2m3ccv83f74yu3cjujfs8kfq823vqv6k2zyta6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHduTmNxQSBBL2l3M2Uw
            QUVZRWFrQmhDWVVIc1BBZ2cyMkF3VnN3a3gydTRJVkZoek0ydgpxa1o4bC9pb3Fi
            d2d6NWFiN3Bka0wvL1Z2SDdvZllLelpCaVpCbzNFMWJNCi0tLSBkeGI3WGxFNlJs
            VVhTOCtRZEhLZDRZSUNzK3RrYXVWZDNSUXRjTWczNmFvCmAzIbpwOZZRoGfK6I1b
            AC7Gg2jEv4g6Yd2dCTWslYe+7ktdxct2YZZNo/5oXIFGVR7KCLFCWCHlxCpJu5hj
            I08=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q0wmqzjaxwgndf94hd7t37dx7wd45qwwk0r7zfytkasd6f5lvc70w89lwgg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDFJWnhYUSBBcnBLdnRM
            VHFMMVppeUZsbENKRzJ3Tmt2Q3NSREJtMjRtRk1kdWNJSmZrNAphTEhseFYyZEF4
            akUyQzZObCsvRU5acmVXZExPVWwzWEdtVWdEWEwvc2VzCi0tLSBFeVF2OFNzU3pH
            RmwrRzFqTHFUL21XYVFNelRXQkJUSjRqVXJsM1FSRjRRCrLfUV54hnfy5pvogGFr
            5ZyPZN77ckv3aIN/VIkHJ88g2Nt/5PuElph5XvrIbApaCKxMpxlUZQkMD3BzQsoI
            CPA=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T19:58:52Z"
    mac: ENC[AES256_GCM,data:UMfUf7vZVBl6rFWUhmV5psR2aH2nQB4xDGIIs2OHS0kCMEoleGolv9ziHngBwVjU84t0DZUPRyedQyR5EBZocibSgs8cOBpyJuVvc7Mgy/YwNDWOqEbOhgCcMKrwZbdsdy2IIrnoTemAqoG/GyNcjgImpahpIM8lNSp2jZgPmFY=,iv:baC59ZjRiRtncXPIHtWWw6CmbaYmlEMVN/dQpbCI+RQ=,tag:kQUujyB814MK2zgTsjAhyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
