pushover_app_key: ENC[AES256_GCM,data:SS+Kxzu8YdPPI2os9l7j0baz53FIxNIi33gmBPCs,iv:TfOHD+smbWS6GYdcMNBBOxHJZMcQGZ0EyIMo1/4VdEQ=,tag:I3I6bfiQNgmsLu9OOc2qyg==,type:str]
pushover_user_key: ENC[AES256_GCM,data:tcQJFPh8647QbQuIk4ZZJiwZoRWjtyO4twt0eI5H,iv:QtQbFYdAMD4LeDcUwcIOHRz5cyIeV2P14TMRB1qla8I=,tag:vJ6b9MWJxz0Td/sz3+g2Gg==,type:str]
sops:
    hc_vault:
        - vault_address: https://vault.local.salamon.xyz
          engine_path: transit
          key_name: sops-key
          created_at: "2026-04-03T13:00:42Z"
          enc: vault:v1:BvBrW4yhHU5nopefebCJaAlLha7KQjzskk+pGzHI97PlvxnTKhTYKojJ+6w9r+CQbHD1MM9KDpwwgy1B
    age:
        - recipient: age1yubikey1qw8ddwxjsp2zdrajc5kk2m3ccv83f74yu3cjujfs8kfq823vqv6k2zyta6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHduTmNxQSBBblMzUGQw
            azZFY1dPcWx4a1lNNnNSVXQydnJYRlNyV2ZjL2lzRm42QmVoegplM2lWOTZhSysz
            cGZSWkFrTnNKZUhXbGUrRFhhZFFhUjNTUWpCR0ZscTdNCi0tLSB2MDNvMEpudFQx
            UFQrbXBvandYZ2p5bVAzUm5EMUJTcVUxa24veUlQL3dFCpR6meB0bnngniV5Ikqm
            OAK/kNrVMEqwuc9D3rTfC93rEfnrkb/PvTY7DSIuVr8dDlxrd5p5L+lLdteP9W/V
            flU=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q0wmqzjaxwgndf94hd7t37dx7wd45qwwk0r7zfytkasd6f5lvc70w89lwgg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDFJWnhYUSBBL1FDSFJM
            S3gyS3BsamlPOE83bVpOUE1TYlJrcVNXTlZwbkl1enlQMHpzRgpMYm1GRkJSSEo0
            V0ZzV3g3cXQ2Y0dUcFo5RmR0RFNpSGZycnUzNUdwYms4Ci0tLSBxdC9QSFNaQTJp
            cVd5S1RlSTZxbktTOGZLaXhta3B0Z2NOTER2dHp3YTdjCtGwP/fanAyLnOBJNHnW
            g47ga5rZOnqd9SHjQMKcL0g6b7VKu+03yj0gXFkti55WFyvIUlWwYyX2lGtiwWGu
            CD8=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T13:00:42Z"
    mac: ENC[AES256_GCM,data:PQxmfeRkAu/iZVexykNKpgjPOWLJeFHDP3h5dsb2hFOfDmsj3Ajh+8tGY9fcPge7lud8swm/sL9s9b0VyC1T7la5Jm5RrfiGNAM5Rb6yz5nMeQqndDOBa0HHVgnfJ40utVFzFNe9+DIyOUf/8JutRIqY1B+OkDhSsHTiib1uYF8=,iv:vhO7wiBaYYceayI8ffI1+3nhcoSVLzd1zjY6WkBmKR4=,tag:jxbtr9Z27MSAb+2FRJNOVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
