pushover-app-key: ENC[AES256_GCM,data:W1g/ac2h7X43i1ky+Oa4DXmpFC5doOWuZ8s8BBrw,iv:uO5u4HMqYm/Z4xsJjSXFf/ud/nHfDuIyec8F+pHbnDU=,tag:ye2dCMw+ETyQo7aVJPQvRQ==,type:str]
pushover-user-key: ENC[AES256_GCM,data:Qsfac3AlWXwxVCPktWd1bHdUrzcGq1zgMLBNtRFm,iv:sDnbggsD5BMeRfoxzyY6W9s7FRo4pNZ34CTQ2zrKwRk=,tag:InAH5RkdeHalU9UdOqJbcQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOg0phKMml4tg+kH2qZOUVi9NT6roXfiDRTLJ4Si3xtP
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHg0VmZ1USA0THVy
            VXFPckJrS25IeWRuUlRjenlmZmtGUDY1SVNWdkJNMzEzT0g3M0EwCkRIM0pDTXp3
            ejNpSEtOWldMUk5Pc1dFTk05YXhCcHo2M0ROcFlmcEV3clUKLS0tIDFta0w1NWZp
            eWR3UGcwQ09DYXpSNmVzMktTdHoxK20wVHNTWXVTeWVLWmcKLRwLnSaEapPZOP8f
            TC/Em6JX0qHFW+iBkdfmOCVf3wQ5pDcCHMP/4XnOIwP/kSYaFJHqANAQbl/yH4vu
            EDAuMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qw8ddwxjsp2zdrajc5kk2m3ccv83f74yu3cjujfs8kfq823vqv6k2zyta6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHduTmNxQSBBek1kY3c0
            bitBZ0o5dWJUdlNIMjVpWXhTMGF1Ui9YWC9Lc0FpNXByVGFtKwptYjNxUW9KL1Ny
            L2VwNE9mN09WcWhUcEJhaEl6dW5FS0o5bUV1dHlPQkJVCi0tLSBBdUlOMnlGMnBF
            ZDYrMUtjVkR3eDQvYUNjMnJiZmtrNVROWDJJL1VhUDZJCtHgqxw56QXBSrHqs+/k
            sEMYAlqEBBlk/Gy0FXhtbJzNAtr1w75ZQc3oIFxFo57PMVIaXy4/Fcj/nLL1MwnG
            eHI=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q0wmqzjaxwgndf94hd7t37dx7wd45qwwk0r7zfytkasd6f5lvc70w89lwgg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDFJWnhYUSBBM0JGZzZM
            Y2xxL1dQcG9pSXZLcXlxN0tvNmIyZ1BMRUJxNlpCdmYvVjFFcwpKck5FVnZHcnFP
            QzFxK3h0WHRzNllUUnhiTEtOUHNOQU1HbjJTV3JjRzVFCi0tLSBaeEx5QWdna0Nj
            ZnJTMVJCQ2NEVmJ6ME84SGpXdnlybEhjSmJSRFozaS9jCptyIevjx6JXGEuYITFR
            QQC/YJKENmsmm+AgB6rUL9rYYtpdTVBxf9KbQ+DV2SvSXx+hAJOOWqk+rBAhAQua
            FjQ=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T18:34:48Z"
    mac: ENC[AES256_GCM,data:bxq78qJksOdc5g03orov4x/8mbLgRArEoh2wgJvPqhc5e2N3qGZVb1vOCNSHjfREQVrpaKW9x09bLWAR1ReKYgD32XyW7VbtNZ9Q/0S218SB5oEqbdEvBGwbG0cdu1nob4yAPqLZ/w8Vop/HpI/n1SjFscr5b3nCuTvacOBIN+w=,iv:gN+YE3PJVw/S05Cpb1zGDZJhFwQvQs5HSbm+qUadNKw=,tag:UHKCfJXDJ7sJAasCjhGoew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
