name: "build-derivations"

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - "nomad/**"
      - "packages/**"
      - "terraform/**"
      - ".github/workflows/build-packages.yaml"
      - ".github/workflows/terraform-apply.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        machine:
          - host: athena
            system: x86_64-linux
          # - host: callisto
          #   system: aarch64-linux
          # - host: charon
          #   system: x86_64-linux
          # - host: demeter
          #   system: x86_64-linux
          # - host: hermes
          #   system: x86_64-linux
          # - host: icarus
          #   system: x86_64-linux
          # - host: orpheus
          #   system: x86_64-linux
          # - host: penelope
          #   system: x86_64-linux
          # - host: pythia
          #   system: x86_64-linux
          # - host: zeus
          #   system: x86_64-linux

    env:
      SOPS_AGE_SSH_PRIVATE_KEY_FILE: /tmp/git_id_ed25519

    steps:
      - name: Configure SOPS git filter
        run: |
          cat >> ~/.gitconfig <<EOF
          [filter "sops"]
              smudge = sops --decrypt --input-type binary /dev/stdin
              clean = sops --encrypt --input-type binary --output-type binary /dev/stdin
              required = true
          EOF

      - name: Store SSH private key
        run: |
          echo "${{ secrets.AGECRYPT_KEY }}" | base64 -d > $SOPS_AGE_SSH_PRIVATE_KEY_FILE
          chmod 600 $SOPS_AGE_SSH_PRIVATE_KEY_FILE

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - if: matrix.machine.system == 'aarch64-linux'
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: time eval
        run: |
          time nix flake show

      # TODO: this does not work reliably
      - name: Check if build needed
        id: build-needed
        run: |
          nix build .#nixosConfigurations.${{ matrix.machine.host }}.config.system.build.toplevel --dry-run
          nix build .#nixosConfigurations.${{ matrix.machine.host }}.config.system.build.toplevel --dry-run 2> dry-run-output
          echo "needs-build=$(cat dry-run-output | grep 'will be built' &> /dev/null && echo 1 || echo 0)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build system
        if: steps.build-needed.outputs.needs-build == '1'
        run: |
          nix build .#nixosConfigurations.${{ matrix.machine.host }}.config.system.build.toplevel

      - name: Push system
        if: steps.build-needed.outputs.needs-build == '1'
        run: |
          attic login ci https://nix-cache.salamon.xyz ${{ secrets.ATTIC_TOKEN }}
          attic push homelab result -j 2

      - name: Update key-val store
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST -sS --fail-with-body --url "https://kv-proxy.salamon.xyz/builds/nixos-system-${{ matrix.machine.host }}" \
               -H  "Authorization: Bearer ${{ secrets.KV_PROXY_TOKEN }}" \
               -d  "$(readlink result || nix eval --raw --read-only .#nixosConfigurations.${{ matrix.machine.host }}.config.system.build.toplevel)"
